<!DOCTYPE html>
<html>
  <head>
    <title>My Sun Sign Infos</title>
  </head>
  <script>
  function display(element){
    document.getElementById('image').innerHTML = element.alt;
  }
  function revert(){
    document.getElementById('image').innerHTML = "Hover over a sunsign image to display details.";
  }
 </script>
  <style>
  #image{
      width: 650px;
      height: 70px;
      border:5px solid rgb(110, 174, 204);
      background-color: rgb(44, 92, 146);
      background-repeat: no-repeat;
      color:rgb(231, 238, 238);
      background-size: 100%;
      font-family: 'Times New Roman';
      font-size: 150%;
      line-height: 60px;
      text-align: center;
      margin-right: auto;
      margin-left: auto;
  }
  img{
  width: 200px;
  height: 200px;
  border-radius: 50%;
  margin: 9.4px;
  }
  </style>
  <body>
    <div>
    <p id = "image">Hover over a sunsign image to display details.<p>
    <img alt = "Sagittarius are beautiful, loyal and passionate." src = "C:\Users\User\OneDrive\Desktop\asd\Sagittarius-Symbol-Pin.jpg" onmouseover = "display(this)" onmouseout = "revert()">
    <img alt = "Pisces are dreamy, helpful and love everyone!" src = "C:\Users\User\OneDrive\Desktop\asd\61KBd+K-EDL.jpg" onmouseover = "display(this)" onmouseout = "revert()">
    <img alt = "Leo are strong and fearless. They aim for and achieve a lot!" src = "C:\Users\User\OneDrive\Desktop\asd\Leo.png.jpg" onmouseover = "display(this)" onmouseout = "revert()">
    <img alt = "Scorpions are friends for life. They are trustworthy and truthful." src = "C:\Users\User\OneDrive\Desktop\asd\71fLhml-2nL.jpg" onmouseover = "display(this)" onmouseout = "revert()">
    <img alt= "Aquarius are rebellious nature but they are innovative and foward thinking." src = "aquarius.jpg" onmouseover="display(this)" onnmouseout = "revert()">
    <img alt= "Cancer are nurturing and protective of others" src = "cancer.jpg" onmouseover="display(this)" onmouseout="revert()">
    <img alt= "Tauras are stubborn but large capacity of kindness" src = "tauras.jpg" onmouseover="display(this)" onmouseout="revert()">
    <img alt= "Gemini are curius and intellegent people" src = "gemini-soulmates.jpg" onmouseover="display(this)" onmouseout = "revert()">
    <img alt= "Libra are charming and elegant" src = "libra.jpg" onmouseover = "display(this)" onmouseout = "revert()">
    <img alt= "Aries are energetic and outgoing" src = "aries.jpg" onmouseover = "display(this)" onmouseout = "revert()">
    <img alt= "Virgo are very neat and concisous of details" src = "virgo.jpg" onmouseover = "display(this)" onmouseout = "revert()">
    <img alt= "Capricorn are very pratical and ambitious" src = "capricorn.jpg" onmouseover = "display(this)" onmouseout = "revert()">
    </div>
  </body>
</html>
